exclude_obs_keys: ["obj_goal_sensor", "goal_to_agent_gps_compass", "ee_pos", "is_art_sensor", "hier_skill_sensor"]
task_id: 0
type: MonoRearrangePickTask-v0
reward_measure: pick_reward
success_measure: pick_success
env_task_gym_id: "HabitatPick"
task_spec_base_path: ""
task_spec: ""    
update_measures:
  dataset:
    data_path: "data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz"
  task.measurements.mono_nav_to_obj_success: 
    must_call_stop: False 
max_episode_steps: 300
measures_list: 
  - "pick_reward"
  - "pick_success"
  - "ee_to_object_distance.0"
  - "ee_to_rest_distance"
  - "force_terminate"
  - "reward"
  - "did_pick_object"
  - "num_steps"
   