task_id: 9
type: MonoNavRearrangeOpenDrawerTask-v0
reward_measure: art_obj_reward
success_measure: art_obj_success
env_task_gym_id: "HabitatNavOpenCabinetTask"
task_spec_base_path: "skill_chain/pddl"
task_spec: "nav_open_cab"
use_marker_options: ["cab_push_point_5"]
update_measures:
  dataset:
    data_path: "data/datasets/replica_cad/rearrange/v1/{split}/in_drawer_1k_100.json.gz"
  task.measurements.mono_nav_to_obj_success: 
      must_call_stop: False
  # environment.iterator_options:
    # filter_criteria: ["art"]
  task.actions.arm_action:
    grip_controller: SuctionGraspAction
  task.measurements.art_obj_at_desired_state: 
    use_absolute_distance: False
  task:
    success_state: 0.45
    success_reward: 10.0
    slack_reward: 0.0
    measurements:
      art_obj_reward:
        type: MonoArtObjReward
        wrong_grasp_end: True
        grasp_reward: 5.0
        art_at_desired_state_reward: 5.0
        marker_dist_reward: 1.0
        js_vel_pen: 0.0 
    # constraint_violate_pen: 1.0
  # task.measurements: 
    # must_call_stop: False
max_episode_steps: 600
measures_list: 
  - "art_obj_success"
  - "art_obj_reward"
  - "art_obj_state"
  - "art_obj_at_desired_state"
  - "ee_dist_to_marker"
  - "ee_to_rest_distance"
  - "force_terminate"
  - "reward"
  - "did_pick_object"
  - "wrong_pick_marker_measure"
  - "num_steps"