
habitat: 
  gym: 
    obs_keys: 
      - "obj_start_sensor"
      - "obj_goal_sensor"
      - "head_depth"
      - "joint"
      - "ee_pos"
      - "is_holding"
      - "relative_resting_position"
      - "env_task_id_sensor"
      - "is_art_sensor"
      - "hier_skill_sensor"
  dataset: 
    data_path: data/datasets/replica_cad/rearrange/v1/train/easy_hard.json.gz
  task: 
    measurements:
      task_stage_steps:
        type: "MonoTaskStageSteps"
    lab_sensors:
      env_task_sensor:
        type: "EnvTaskSensor"