task_id: 7
type: MonoRearrangeOpenDrawerTask-v0
reward_measure: art_obj_reward
success_measure: art_obj_success
env_task_gym_id: "HabitatOpenCabinet"
task_spec_base_path: ""
task_spec: ""
update_measures:
  task.measurements.art_obj_at_desired_state: 
    use_absolute_distance: False
  task.measurements.art_obj_reward:
    type: MonoArtObjReward
    wrong_grasp_end: True
    grasp_reward: 5.0
    art_at_desired_state_reward: 5.0
    marker_dist_reward: 1.0
    # constraint_violate_pen: 1.0
  task.measurements.mono_nav_to_obj_success: 
      must_call_stop: False
  dataset:
    data_path: "data/datasets/replica_cad/rearrange/v1/{split}/in_drawer_1k_100.json.gz" 
  task.actions.arm_action:
    grip_controller: SuctionGraspAction
  task:
    success_state: 0.45
    success_reward: 10.0
    slack_reward: 0.0
max_episode_steps: 200
measures_list: 
  - "art_obj_success"
  - "art_obj_reward"
  - "art_obj_at_desired_state"
  - "ee_dist_to_marker"
  - "ee_to_object_distance.0"
  - "ee_to_rest_distance"
  - "force_terminate"
  - "reward"
  - "did_pick_object"
  - "num_steps"